#!/usr/bin/env python3
"""OneCommand API contract.

Frontend and backend are generated in parallel (Claude + Codex). Without a
shared contract the frontend guesses the response fields: a real CRM build
shipped `pick(dash, ["winRate", "closeRate", "conversionRate", …])` and showed a
monthly win rate next to all-time won/lost counts ("100 % — 5 won, 2 lost").
The typecheck could not catch it because nothing tied both sides to one shape.

The contract lives in the spec (`api_contract`) and is turned into one
generated TypeScript file both sides import. Route handlers type their bodies
with it (`satisfies DashboardResponse`), the UI types its fetches with it, and
the typecheck in the quality gate then catches every drift.

Spec format
-----------
"api_contract": {
  "types_file": "lib/api-contract.ts",
  "types": {"Deal": {"id": "string", "title": "string", "value": "number",
                     "status": "'open'|'won'|'lost'", "closedAt?": "date|null"}},
  "endpoints": [
    {"name": "Dashboard", "method": "GET", "path": "/api/dashboard", "auth": true,
     "query": {"period?": "'month'|'quarter'|'year'"},
     "response": {"openPipelineValue": "number", "winRate": "number",
                  "pipelineByStage": [{"stageId": "string", "name": "string", "value": "number"}]},
     "metrics": ["open_pipeline", "win_rate"]},
    {"name": "CreateDeal", "method": "POST", "path": "/api/deals", "request": {…}, "response": "Deal"}
  ]
}

Types: string, number, boolean, date (ISO string), null, unknown, 'literal',
a name from "types", unions with "|", arrays with "[]" or [shape]; object keys
ending in "?" are optional; "$nullable": true makes an object "| null".
`"consumer": "external"` marks endpoints no UI reads (public API, webhooks).

Subcommands
-----------
validate  Check the contract (and the spec's metrics) in Phase 1.
types     Generate the TypeScript file (--check: exit 1 when it is stale).
check     Verify a project against its contract (quality gate step "contract"):
          types file current, every endpoint has a route handler exporting its
          method (Next.js App Router), the handler (or a module it imports) and
          the UI reference the generated types. Guessed field names
          (pick(x, ["a", "b", …])) are reported as warnings (⚠).

Exit codes: 0 ok · 1 problems found · 2 usage error · 3 spec has no api_contract
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

METHODS = ("GET", "POST", "PUT", "PATCH", "DELETE")
SCALARS = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean",
           "date": "string", "datetime": "string", "null": "null", "unknown": "unknown"}
NAME = re.compile(r"^[A-Z][A-Za-z0-9]*$")
METRIC_ID = re.compile(r"^[a-z][a-z0-9_-]*$")
IDENT = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")
LITERAL = re.compile(r"""^(?:'[^']*'|"[^"]*"|-?\d+(?:\.\d+)?|true|false)$""")
DEFAULT_TYPES_FILE = "lib/api-contract.ts"
SOURCE_EXT = (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs")
SKIP_DIRS = {"node_modules", ".next", "dist", "build", "out", ".onecommand", ".git", "coverage",
             "e2e", "tests", "test", "__tests__", "playwright-report", "test-results", ".turbo", ".vercel"}
# pick(data, ["winRate", "closeRate", …]) — trying several field names means nobody knew the real one.
GUESS = re.compile(r"""\b(\w*(?:pick|first|coalesce|fallback|oneof|alias)\w*)\s*(?:<[^<>()]*>)?\s*\(\s*[^,()\[\]]+,\s*"""
                   r"""\[\s*(['"])[A-Za-z_]\w*\2(?:\s*,\s*(['"])[A-Za-z_]\w*\3)+\s*,?\s*\]""", re.I)
HEADER = ("// Generated by OneCommand (USC Software UG) from .onecommand-spec.json — do not edit.\n"
          "// Change \"api_contract\" in the spec, then regenerate:\n"
          "//   python3 \"$OC_ROOT/hooks/api-contract.py\" types\n")


class SpecError(Exception):
    pass


def load_spec(path: str) -> dict[str, Any]:
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SpecError(f"spec not found: {path}") from None
    except ValueError as exc:
        raise SpecError(f"spec is not valid JSON ({path}): {exc}") from None


# ─── type language ────────────────────────────────────────────────────────────

def split_union(expr: str) -> list[str]:
    """Split on | outside quotes."""
    parts, buf, quote = [], "", ""
    for ch in expr:
        if quote:
            buf += ch
            if ch == quote:
                quote = ""
        elif ch in "'\"":
            quote, buf = ch, buf + ch
        elif ch == "|":
            parts.append(buf.strip())
            buf = ""
        else:
            buf += ch
    parts.append(buf.strip())
    return parts


def check_type(value: Any, where: str, named: set[str], errors: list[str]) -> None:
    if isinstance(value, str):
        for atom in split_union(value):
            base = atom[:-2].strip() if atom.endswith("[]") else atom
            if not base:
                errors.append(f"{where}: empty type in '{value}'")
            elif not (base in SCALARS or base in named or LITERAL.match(base)):
                errors.append(f"{where}: unknown type '{base}' — use string, number, boolean, date, null, "
                              f"unknown, 'literal' or a name from api_contract.types")
    elif isinstance(value, list):
        if len(value) != 1:
            errors.append(f"{where}: an array shape holds exactly one element type, got {len(value)}")
        else:
            check_type(value[0], f"{where}[]", named, errors)
    elif isinstance(value, dict):
        fields = {k: v for k, v in value.items() if not k.startswith("$")}
        if not fields:
            errors.append(f"{where}: empty object — name its fields")
        for key, sub in fields.items():
            if not key.rstrip("?"):
                errors.append(f"{where}: empty field name")
            check_type(sub, f"{where}.{key}", named, errors)
    else:
        errors.append(f"{where}: a type is a string, a one-element list or an object, got {type(value).__name__}")


def ts_type(value: Any, indent: int = 0) -> str:
    if isinstance(value, str):
        out = []
        for atom in split_union(value):
            arr = atom.endswith("[]")
            base = atom[:-2].strip() if arr else atom
            t = SCALARS.get(base, base)
            if base.startswith('"') or base.startswith("'"):
                t = json.dumps(base[1:-1])
            out.append(f"Array<{t}>" if arr else t)
        return " | ".join(out)
    if isinstance(value, list):
        return f"Array<{ts_type(value[0], indent)}>"
    pad = "  " * (indent + 1)
    lines = ["{"]
    for key, sub in value.items():
        if key.startswith("$"):
            continue
        optional = key.endswith("?")
        name = key[:-1] if optional else key
        prop = name if IDENT.match(name) else json.dumps(name)
        lines.append(f"{pad}{prop}{'?' if optional else ''}: {ts_type(sub, indent + 1)};")
    lines.append("  " * indent + "}")
    body = "\n".join(lines)
    return f"{body} | null" if value.get("$nullable") else body


# ─── validate ─────────────────────────────────────────────────────────────────

def needs_contract(spec: dict[str, Any]) -> bool:
    if spec.get("app_type") in ("game", "os"):
        return False
    return "web" in (spec.get("build_targets") or ["web"])


def validate(spec: dict[str, Any], allow_missing: bool = False) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    notes: list[str] = []
    contract = spec.get("api_contract")
    metrics = spec.get("metrics") or []

    metric_ids: set[str] = set()
    if not isinstance(metrics, list):
        errors.append("metrics must be a list")
        metrics = []
    for i, m in enumerate(metrics):
        where = f"metrics[{i}]"
        if not isinstance(m, dict):
            errors.append(f"{where}: must be an object")
            continue
        mid = m.get("id", "")
        if not METRIC_ID.match(str(mid)):
            errors.append(f"{where}: id '{mid}' must be lower_snake_case")
        elif mid in metric_ids:
            errors.append(f"{where}: duplicate metric id '{mid}'")
        metric_ids.add(str(mid))
        for field in ("label", "definition", "period"):
            if not str(m.get(field, "")).strip():
                errors.append(f"metric '{mid}': '{field}' is required — one definition, one period, one label "
                              f"that every page uses")

    if contract is None:
        if needs_contract(spec) and not allow_missing:
            errors.append("spec has no api_contract — define every endpoint's request and response so frontend "
                          "and backend share one shape (an app without API: \"api_contract\": {\"endpoints\": []})")
        return errors, notes
    if not isinstance(contract, dict):
        return errors + ["api_contract must be an object"], notes

    named_types = contract.get("types") or {}
    if not isinstance(named_types, dict):
        errors.append("api_contract.types must map a TypeName to its shape")
        named_types = {}
    named = set(named_types)
    for tname, shape in named_types.items():
        if not NAME.match(tname):
            errors.append(f"api_contract.types: '{tname}' must be PascalCase")
        check_type(shape, f"types.{tname}", named, errors)

    endpoints = contract.get("endpoints")
    if not isinstance(endpoints, list):
        return errors + ["api_contract.endpoints must be a list"], notes
    names: set[str] = set()
    generated: set[str] = set(named)
    routes: set[tuple[str, str]] = set()
    used_metrics: set[str] = set()
    for i, ep in enumerate(endpoints):
        if not isinstance(ep, dict):
            errors.append(f"endpoints[{i}]: must be an object")
            continue
        name = str(ep.get("name", ""))
        where = f"endpoint {name or i}"
        if not NAME.match(name):
            errors.append(f"endpoints[{i}]: name '{name}' must be PascalCase (types are <Name>Response, <Name>Request)")
        elif name in names:
            errors.append(f"{where}: duplicate name")
        names.add(name)
        method = str(ep.get("method", "")).upper()
        path = str(ep.get("path", ""))
        if method not in METHODS:
            errors.append(f"{where}: method must be one of {', '.join(METHODS)}")
        if not path.startswith("/"):
            errors.append(f"{where}: path must start with / (got '{path}')")
        if (method, normalize_path(path)) in routes:
            errors.append(f"{where}: {method} {path} is defined twice")
        routes.add((method, normalize_path(path)))
        if "response" not in ep:
            errors.append(f"{where}: 'response' is required (null for an empty body)")
        for part in ("query", "request", "response"):
            if ep.get(part) is not None:
                check_type(ep[part], f"{where}.{part}", named, errors)
        if method in ("POST", "PUT", "PATCH") and ep.get("request") is None and not ep.get("no_body"):
            notes.append(f"{where}: {method} without 'request' — set \"no_body\": true if that is intended")
        for suffix in ("Response", "Request", "Query"):
            if f"{name}{suffix}" in generated:
                errors.append(f"{where}: type name {name}{suffix} collides with api_contract.types")
        if ep.get("consumer", "ui") not in ("ui", "external"):
            errors.append(f"{where}: consumer must be 'ui' or 'external'")
        for mid in ep.get("metrics") or []:
            if mid not in metric_ids:
                errors.append(f"{where}: metric '{mid}' is not defined in spec.metrics")
            used_metrics.add(mid)
    if endpoints:
        for mid in sorted(metric_ids - used_metrics):
            errors.append(f"metric '{mid}' is served by no endpoint — list it in the 'metrics' of the endpoint "
                          f"that computes it (one server function per metric)")
    return errors, notes


def cmd_validate(args: argparse.Namespace) -> int:
    spec = load_spec(args.spec)
    errors, notes = validate(spec, args.allow_missing)
    for n in notes:
        print(f"  ○ {n}")
    for e in errors:
        print(f"  ✗ {e}")
    if errors:
        print(f"[contract] {len(errors)} problem(s) in api_contract / metrics")
        return 1
    contract = spec.get("api_contract") or {}
    print(f"[contract] valid — {len(contract.get('endpoints') or [])} endpoints, "
          f"{len(contract.get('types') or {})} shared types, {len(spec.get('metrics') or [])} metrics")
    return 0


# ─── types ────────────────────────────────────────────────────────────────────

def render_types(spec: dict[str, Any]) -> str:
    contract = spec.get("api_contract") or {}
    metrics = {m["id"]: m for m in spec.get("metrics") or [] if isinstance(m, dict) and "id" in m}
    out = [HEADER]
    for tname, shape in (contract.get("types") or {}).items():
        if isinstance(shape, dict) and not shape.get("$nullable"):
            out.append(f"export interface {tname} {ts_type(shape)}\n")
        else:
            out.append(f"export type {tname} = {ts_type(shape)};\n")
    api_lines = []
    for ep in contract.get("endpoints") or []:
        name, method, path = ep["name"], ep["method"].upper(), ep["path"]
        doc = [f"{method} {path}" + (" (auth)" if ep.get("auth") else "")]
        for mid in ep.get("metrics") or []:
            m = metrics.get(mid, {})
            doc.append(f"metric {mid}: {m.get('label', '')} — {m.get('definition', '')} [{m.get('period', '')}]")
        out.append("/** " + "\n *  ".join(doc) + " */")
        for part, suffix in (("query", "Query"), ("request", "Request"), ("response", "Response")):
            shape = ep.get(part)
            if part == "response" and shape is None:
                out.append(f"export type {name}Response = null;")
            elif shape is not None:
                if isinstance(shape, dict) and not shape.get("$nullable"):
                    out.append(f"export interface {name}{suffix} {ts_type(shape)}")
                else:
                    out.append(f"export type {name}{suffix} = {ts_type(shape)};")
        out.append("")
        api_lines.append(f"  {name}: {{ method: {json.dumps(method)}, path: {json.dumps(path)} }},")
    out.append("export const API = {")
    out.extend(api_lines)
    out.append("} as const;\n")
    if metrics:
        out.append("/** Metric labels: every page that shows a metric uses this label (it names the period). */")
        out.append("export const METRICS = {")
        for mid, m in metrics.items():
            out.append(f"  {json.dumps(mid)}: {{ label: {json.dumps(m.get('label', ''), ensure_ascii=False)}, "
                       f"period: {json.dumps(m.get('period', ''), ensure_ascii=False)} }},")
        out.append("} as const;\n")
    return "\n".join(out)


def types_path(spec: dict[str, Any], project: Path, override: str | None = None) -> Path:
    rel = override or (spec.get("api_contract") or {}).get("types_file") or DEFAULT_TYPES_FILE
    return (project / rel).resolve() if not os.path.isabs(rel) else Path(rel)


def cmd_types(args: argparse.Namespace) -> int:
    spec = load_spec(args.spec if os.path.isabs(args.spec) else str(Path(args.project_dir) / args.spec))
    if spec.get("api_contract") is None:
        print("[contract] spec has no api_contract — nothing to generate")
        return 3
    errors, _ = validate(spec)
    if errors:
        for e in errors:
            print(f"  ✗ {e}")
        print("[contract] fix the contract first (api-contract.py validate)")
        return 1
    target = types_path(spec, Path(args.project_dir), args.out)
    content = render_types(spec)
    current = target.read_text(encoding="utf-8") if target.exists() else None
    if args.check:
        if current == content:
            print(f"[contract] {target} is current")
            return 0
        print(f"[contract] {target} is {'missing' if current is None else 'stale'} — run api-contract.py types")
        return 1
    if current != content:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    print(f"[contract] wrote {target} ({len((spec['api_contract'].get('endpoints') or []))} endpoints)")
    return 0


# ─── check ────────────────────────────────────────────────────────────────────

def normalize_path(path: str) -> tuple[str, ...]:
    """'/api/deals/:id' → ('api', 'deals', ':'); [id] and {id} are params too."""
    segs = []
    for seg in path.split("?")[0].strip("/").split("/"):
        if not seg:
            continue
        if seg.startswith(":") or (seg.startswith("{") and seg.endswith("}")) or (seg.startswith("[") and seg.endswith("]")):
            segs.append("*" if seg.strip("[]{}:").startswith("...") else ":")
        else:
            segs.append(seg)
    return tuple(segs)


def route_files(project: Path) -> list[tuple[tuple[str, ...], Path]]:
    """Next.js App Router handlers: app/**/route.ts → URL segments (groups and slots dropped)."""
    found = []
    for app_dir in (project / "app", project / "src" / "app"):
        if not app_dir.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(app_dir):
            # Folders like app/api/test/ are real URL segments — skip only build output here.
            dirnames[:] = [d for d in dirnames if d not in {"node_modules", ".next"}]
            for fn in filenames:
                if re.match(r"^route\.(ts|tsx|js|mjs)$", fn):
                    rel = Path(dirpath).relative_to(app_dir).parts
                    segs = []
                    for seg in rel:
                        if (seg.startswith("(") and seg.endswith(")")) or seg.startswith("@"):
                            continue
                        if seg.startswith("[[...") or seg.startswith("[..."):
                            segs.append("*")
                        elif seg.startswith("[") and seg.endswith("]"):
                            segs.append(":")
                        else:
                            segs.append(seg)
                    found.append((tuple(segs), Path(dirpath) / fn))
    return found


def match_route(want: tuple[str, ...], routes: list[tuple[tuple[str, ...], Path]]) -> Path | None:
    """Most specific handler for an endpoint path, as Next.js resolves it: static segments beat
    [param], [param] beats [...catchAll]. A [param] handler serves any value (/api/reports/[type]
    serves /api/reports/winrate)."""
    best: tuple[int, Path] | None = None
    for segs, path in routes:
        if segs and segs[-1] == "*":
            head, rest_ok = segs[:-1], len(want) >= len(segs) - 1
        else:
            head, rest_ok = segs, len(want) == len(segs)
        if not rest_ok:
            continue
        score = 0
        for a, b in zip(head, want):
            if a == b:
                score += 2
            elif a == ":":
                score += 1
            else:
                break
        else:
            score -= 1 if segs and segs[-1] == "*" else 0
            if best is None or score > best[0]:
                best = (score, path)
    return best[1] if best else None


def exports_method(source: str, method: str) -> bool:
    return bool(re.search(rf"export\s+(?:async\s+)?function\s+{method}\b|export\s+const\s+{method}\b"
                          rf"|export\s*\{{[^}}]*\b(?:as\s+)?{method}\b[^}}]*\}}", source))


def local_imports(file: Path, project: Path) -> list[Path]:
    """Direct relative and @/ imports of a module, resolved to files."""
    try:
        source = file.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    result = []
    for spec in re.findall(r"""(?:from|import)\s*\(?\s*['"]([^'"]+)['"]""", source):
        if spec.startswith("."):
            bases = [file.parent / spec]
        elif spec.startswith("@/") or spec.startswith("~/"):
            bases = [project / spec[2:], project / "src" / spec[2:]]
        else:
            continue
        for base in bases:
            for cand in [base] + [base.with_name(base.name + ext) for ext in SOURCE_EXT] + \
                        [base / f"index{ext}" for ext in SOURCE_EXT]:
                if cand.is_file():
                    result.append(cand)
                    break
    return result


def source_files(project: Path) -> list[Path]:
    files = []
    for dirpath, dirnames, filenames in os.walk(project):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")]
        files.extend(Path(dirpath) / fn for fn in filenames if fn.endswith(SOURCE_EXT))
    return files


def mentions(file: Path, word: str, cache: dict[Path, str]) -> bool:
    if file not in cache:
        try:
            cache[file] = file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            cache[file] = ""
    return re.search(rf"\b{re.escape(word)}\b", cache[file]) is not None


def check(spec: dict[str, Any], project: Path) -> tuple[list[str], list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    notes: list[str] = []
    contract = spec["api_contract"]
    v_errors, _ = validate(spec)
    if v_errors:
        return [f"contract invalid: {e}" for e in v_errors], warnings, notes

    types_file = types_path(spec, project)
    expected = render_types(spec)
    current = types_file.read_text(encoding="utf-8") if types_file.exists() else None
    rel_types = os.path.relpath(types_file, project)
    if current is None:
        errors.append(f"{rel_types} is missing — generate it: python3 \"$OC_ROOT/hooks/api-contract.py\" types")
    elif current != expected:
        errors.append(f"{rel_types} differs from the contract in the spec — never edit it by hand: change "
                      f"api_contract in .onecommand-spec.json and run api-contract.py types")

    routes = route_files(project)
    files = [f for f in source_files(project) if f.resolve() != types_file]
    cache: dict[Path, str] = {}
    route_set = {p.resolve() for _, p in routes}
    # Everything that is not a route handler counts as UI side: pages, components, client modules and
    # shared server functions a page calls directly.
    ui_files = [f for f in files if f.resolve() not in route_set
                and not re.search(r"(^|/)(src/)?app/api/", f.relative_to(project).as_posix())]
    if not routes:
        notes.append("no Next.js route handlers (app/**/route.ts) — route existence not checked; "
                     "types must still be referenced by the server code")

    for ep in contract.get("endpoints") or []:
        name, method, path = ep["name"], ep["method"].upper(), ep["path"]
        label = f"{method} {path} ({name})"
        response_type = f"{name}Response" if ep.get("response") is not None else None
        if routes:
            handler = match_route(normalize_path(path), routes)
            if handler is None:
                errors.append(f"{label}: no route handler — expected app{path_hint(path)}/route.ts")
                continue
            source = handler.read_text(encoding="utf-8", errors="replace")
            rel = os.path.relpath(handler, project)
            if not exports_method(source, method):
                errors.append(f"{label}: {rel} does not export {method}")
            if response_type:
                scope = [handler] + local_imports(handler, project)
                if not any(mentions(f, response_type, cache) for f in scope):
                    errors.append(f"{label}: {rel} (or a module it imports) never uses {response_type} — type the "
                                  f"body: NextResponse.json(body satisfies {response_type})")
        elif response_type and not any(mentions(f, response_type, cache) for f in files):
            errors.append(f"{label}: no source file uses {response_type} — type the server response with it")
        if (response_type and method == "GET" and ep.get("consumer", "ui") == "ui"
                and not any(mentions(f, response_type, cache) for f in ui_files)):
            errors.append(f"{label}: no page, component or client module uses {response_type} — type the fetch "
                          f"(e.g. api<{response_type}>(API.{name}.path)) or mark the endpoint \"consumer\": \"external\"")

    for f in files:
        text = cache.get(f)
        if text is None:
            text = cache[f] = f.read_text(encoding="utf-8", errors="replace")
        for m in GUESS.finditer(text):
            line = text.count("\n", 0, m.start()) + 1
            warnings.append(f"{os.path.relpath(f, project)}:{line}: {m.group(1)}(…, [several field names]) guesses the "
                            f"response shape — read the field the contract names")
    return errors, warnings, notes


def path_hint(path: str) -> str:
    return "/" + "/".join(f"[{s.strip(':{}[]')}]" if s.startswith((":", "{", "[")) else s
                          for s in path.split("?")[0].strip("/").split("/"))


def cmd_check(args: argparse.Namespace) -> int:
    project = Path(args.project_dir).resolve()
    spec_path = args.spec if os.path.isabs(args.spec) else str(project / args.spec)
    spec = load_spec(spec_path)
    if spec.get("api_contract") is None:
        print("[contract] spec has no api_contract — not applicable")
        return 3
    errors, warnings, notes = check(spec, project)
    for n in notes:
        print(f"  ○ {n}")
    for w in warnings:
        print(f"  ⚠ {w}")
    for e in errors:
        print(f"  ✗ {e}")
    n = len(spec["api_contract"].get("endpoints") or [])
    if errors:
        print(f"[contract] error: {len(errors)} contract violation(s) across {n} endpoints")
        return 1
    print(f"[contract] {n} endpoints match the contract" + (f" — {len(warnings)} warning(s)" if warnings else ""))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("validate", help="check api_contract and metrics in the spec")
    p.add_argument("--spec", default=".onecommand-spec.json")
    p.add_argument("--allow-missing", action="store_true", help="a spec without api_contract is fine")
    p.set_defaults(func=cmd_validate)

    p = sub.add_parser("types", help="generate the TypeScript contract file")
    p.add_argument("--spec", default=".onecommand-spec.json")
    p.add_argument("--project-dir", default=".")
    p.add_argument("--out", help="override api_contract.types_file")
    p.add_argument("--check", action="store_true", help="exit 1 when the file is missing or stale; write nothing")
    p.set_defaults(func=cmd_types)

    p = sub.add_parser("check", help="verify the project against its contract")
    p.add_argument("--project-dir", default=".")
    p.add_argument("--spec", default=".onecommand-spec.json")
    p.set_defaults(func=cmd_check)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except SpecError as exc:
        print(f"[contract] {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
