// Generated by OneCommand (hooks/api-contract.py) from .onecommand-spec.json — do not edit.
// Change "api_contract" in the spec, then regenerate:
//   python3 "$OC_ROOT/hooks/api-contract.py" types

export interface Note {
  id: number;
  title: string;
}

/** GET /api/notes */
export type ListNotesResponse = Array<Note>;

/** POST /api/notes */
export interface CreateNoteRequest {
  title: string;
}
export type CreateNoteResponse = Note;

export const API = {
  ListNotes: { method: "GET", path: "/api/notes" },
  CreateNote: { method: "POST", path: "/api/notes" },
} as const;
